/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ipanonymizerpipeline;

import static org.junit.jupiter.api.Assertions.assertEquals;
import java.io.IOException;
import java.nio.ByteBuffer;
import org.capnproto.ArrayOutputStream;
import org.junit.jupiter.api.Test;



class AppTest {

    ByteBuffer getMockBuffer () throws IOException {
        org.capnproto.MessageBuilder message = new org.capnproto.MessageBuilder();
        HtmlLog.HttpLogRecord.Builder httpLog = message.initRoot(HtmlLog.HttpLogRecord.factory);
        
        httpLog.setTimestampEpochMilli(1710335474); // 2024-03-13 13:11:14	
        httpLog.setResourceId(582757444);
        httpLog.setBytesSent(2075190);
        httpLog.setRequestTimeMilli(7543);
        httpLog.setResponseStatus((short) 502);
        httpLog.setCacheStatus("HIT");
        httpLog.setMethod("GET");
        httpLog.setRemoteAddr("170.172.222.100");
        httpLog.setUrl("/a/b/media/files/5wd1hue25guwva88lmrt4lspboq0ft5fd30jqglwd4humzt5zbqcr.json");

        ByteBuffer buf = ByteBuffer.allocate(512);

        org.capnproto.Serialize.write(new ArrayOutputStream(buf), message);
        
        return buf;
    }


    @Test 
    void capnpDecodingTest() throws IOException {

        HtmlLog.HttpLogRecord.Reader httpLog = CapnpDeserializer.getDeserializer(getMockBuffer());

        assertEquals(1710335474, httpLog.getTimestampEpochMilli());
        assertEquals(582757444, httpLog.getResourceId());
        assertEquals(2075190, httpLog.getBytesSent());
        assertEquals(7543, httpLog.getRequestTimeMilli());
        assertEquals(502, httpLog.getResponseStatus());
        assertEquals("HIT", httpLog.getCacheStatus().toString());
        assertEquals("GET", httpLog.getMethod().toString());
        assertEquals("170.172.222.100", httpLog.getRemoteAddr().toString());
        assertEquals("/a/b/media/files/5wd1hue25guwva88lmrt4lspboq0ft5fd30jqglwd4humzt5zbqcr.json", httpLog.getUrl().toString());
    }


    @Test
    void anonymizeIpTest() {
        assertEquals("170.172.222.X", Anonymizer.anonymizeIp("170.172.222.100"));
    }
}
